### ISSUE TITLE
Add a difficulty sort

### ISSUE THREAD

**Issue by monizb** [monizb/hacktoberfest-swag-list#13]
**Is your feature request related to a problem? Please describe.**
Right now every swag opportunity has a key:  "no_of_prs": 1,  which tells the minimum number of PRs required to achieve the swag

**Describe the solution you'd like**
Add a sort button to sort the list based on Most difficult --> Least difficult and vice versa, we should also be able to remove the sort and get back the normal list

**Comment by kodelebah** [comment]
What's the object key on list.json file that can I use to sort it by difficulty?

**Comment by monizb** [comment]
This one: no_of_prs

**Comment by kodelebah** [comment]
Okay, I will try it. Please assign me

**Comment by kodelebah** [comment]
When I sorting the list, do you want the alphabets stay in order? like A, B, C...

**Comment by monizb** [comment]
Not required 😬
