### ISSUE TITLE
[NEW] Swag Opportunity  🎉 

### ISSUE THREAD

**Issue by debxrshi** [monizb/hacktoberfest-swag-list#158]
**Name Of Organization**
Activeloop 
**Description**
Regardless of what issue you will be resolving, any contribution will be rewarded with Activeloop swag!
**Swag Items**
Headphones, T-shirts, Stickers

**Link to proof**
https://www.activeloop.ai/hacktoberfest/

**Comment by su-shubham** [comment]
Share the link for Activeloop X hacktoberfest 2022.
