### ISSUE TITLE
[NEW] Swag Opportunity  🎉 

### ISSUE THREAD

**Issue by debxrshi** [monizb/hacktoberfest-swag-list#160]
**Name Of Organization**
StepZen
**Description**
Join us for Hacktoberfest 2022 by contributing to StepZen
**Swag Items**
Tshirt, Sticker
**Link to proof**
https://stepzen.com/blog/stepzen-hacktoberfest-2022

**Comment by debxrshi** [comment]
Please help out with the PR issue: https://github.com/monizb/hacktoberfest-swag-list/pull/161

**Comment by yashkc2025** [comment]
please label the issue as hacktoberfest
