### ISSUE TITLE
[NEW] Swag Opportunity  🎉 

### ISSUE THREAD

**Issue by idivyanshbansal** [monizb/hacktoberfest-swag-list#19]
**Name Of Organization**
Globo

**Description**
- Contribute to two pull requests in any in any eligible repo during the month of October.
- Ensure that at least one pull request is merged.
- 
**Swag Items**
T-shirt

**Link to proof**
https://hacktoberfest.globo.com/

**Comment by monizb** [comment]
Globo is already a part of the list 😁 @idivyanshbansal
