### ISSUE TITLE
Add a Pageview/Hit Counter

### ISSUE THREAD

**Issue by monizb** [monizb/hacktoberfest-swag-list#30]
**Is your feature request related to a problem? Please describe.**
There is no page view/hit counter currently showing the number of visitors to the page

**Describe the solution you'd like**
Use an external library or anything else that fits the theme and shows the total visitor count to the Swag List

**Comment by thieleju** [comment]
Hi, can I work on this? 😄

**Comment by rajputarjun2001** [comment]
Hi @monizb I want to work on this, Could you please assign it?

**Comment by monizb** [comment]
@thieleju please go ahead!

**Comment by monizb** [comment]
> Hi @monizb I want to work on this, Could you please assign it?

You can take up the next one 😬

**Comment by thieleju** [comment]
Hi @monizb, can you please review my pr #47 ? 

If the design/functionality is not as desired, please feel free say so! This was my first time working with react 😅

**Comment by monizb** [comment]
@thieleju You are amazing, thanks!
