### ISSUE TITLE
UI/UX Improvement

### ISSUE THREAD

**Issue by manavmodi22** [monizb/hacktoberfest-swag-list#37]
**Is your feature request related to a problem? Please describe.**
When the page is visited all the tags look the same to eye, which is hard to be able to distinguish between them.

**Describe the solution you'd like**
A much cooler way to show tags would be to color code them.

**Describe alternatives you've considered**
Any other way to enhance the visibility is also welcomed!

**Additional context**
None.

**Comment by monizb** [comment]
@manavmodi22 Let's do it so that when the page first loads, we create a unique color for each unique tag, and the recurring tags can take in the same color, so this will result in different colors on every refresh as well, what say?

**Comment by manavmodi22** [comment]
Implementing this might be problem, given that anyone can assign any tag to an opportunity. Maybe a list of tags that have colors assigned would make a greater sense here.

**Comment by monizb** [comment]
Cool lets have one consistent list and the other ones not on the list can take a default color

**Comment by wsameer** [comment]
@manavmodi22 if you guys have decided on the `colors:tag` mapping then I can take this up.
Also let me know the default color for new tags. TIA.

**Comment by monizb** [comment]
Hi @wsameer , yes we have decided on that, lets have a default list with: ["Tshirt","Stickers","Bottle","Socks","Hoodie"] as the defaults with each having a color and en emoji (if there is one available) and the rest defaults can have the current tag color :)

**Comment by wsameer** [comment]
@monizb  what emoji do you want to show for tags outside `["Tshirt","Stickers","Bottle","Socks","Hoodie"]` ?
