### ISSUE TITLE
[NEW] Swag Opportunity  🎉 

### ISSUE THREAD

**Issue by bineethkumar** [monizb/hacktoberfest-swag-list#48]
**Name Of Organization**
Dev.to

**Description**
Get Hacktoberfest 2021 Profile Badge in Dev.to profile by sharing your Hacktoberfest Experience with #hacktoberfest on the post.

**Swag Items**
Hacktoberfest 2021 Profile Badge in Dev.to website

**Link to proof**
https://dev.to/devteam/hacktoberfest-2021-is-here-4a3l

**Comment by monizb** [comment]
Thanks @bineethkumar !

**Comment by bineethkumar** [comment]
Can I take this?
