### ISSUE TITLE
[NEW] Swag Opportunity  🎉 

### ISSUE THREAD

**Issue by pankaj892** [monizb/hacktoberfest-swag-list#49]
**Name Of Organization**
Mayadata

**Description**
Contribute to OpenEBS and after PRs are merged special swags for them will be sent by Mayadata

**Swag Items**
T-Shirt,Oculus VR(Grand Prize)

**Link to proof**
https://blog.mayadata.io/celebrate-hacktoberfest-2021-support-open-source-with-mayadata-openebs

**Comment by monizb** [comment]
Thanks @pankaj892 !
