### ISSUE TITLE
Add a search box to filter swag opportunities

### ISSUE THREAD

**Issue by monizb** [monizb/hacktoberfest-swag-list#6]
**Is your feature request related to a problem? Please describe.**
There is currently no search box to filter out swag opportunities

**Describe the solution you'd like**
Add a simple search box on top of the list to filter out results from Both name of the organization and from the swag tags as the user is typing in the search query

**Comment by SamikshaSankar** [comment]
Please assign me

**Comment by monizb** [comment]
Go ahead @SamikshaSankar !

**Comment by kodelebah** [comment]
Hello @SamikshaSankar, are you still working on this? I'd like to help or take over if you don't have the time.

**Comment by SamikshaSankar** [comment]
@monizb Can u tell me where I can insert the code of html css js

**Comment by kodelebah** [comment]
Please assign me

**Comment by monizb** [comment]
> @monizb Can u tell me where I can insert the code of html css js

Its react code, so you will have to change the specific file

**Comment by monizb** [comment]
Hi @kodelebah do you want to look at #13

**Comment by kodelebah** [comment]
> Hi @kodelebah do you want to look at #13

Oh okay, I will try it. Btw, I've create the branch for this issue to try adding the search box. If you need help for this issue also, I hope you can assign to me 😁

**Comment by SamikshaSankar** [comment]
@monizb assign this issue to @kodelebah

**Comment by monizb** [comment]
@kodelebah do you want to take this up as well?

**Comment by kodelebah** [comment]
> @kodelebah do you want to take this up as well?

Of course, with pleasure. But I will do it later, because I've other task.

**Comment by monizb** [comment]
> > @kodelebah do you want to take this up as well?
> 
> Of course, with pleasure. But I will do it later, because I've other task.

Take your time thanks!
