### ISSUE TITLE
Add a tag filter to the list

### ISSUE THREAD

**Issue by monizb** [monizb/hacktoberfest-swag-list#7]
**Is your feature request related to a problem? Please describe.**
Right now when the swag tags are clicked on nothing happens

**Describe the solution you'd like**
When the tag is clicked for example "Tshirt" then the list should filter out all the organizations which are giving out Tshirts as swag

**Comment by sprakash57** [comment]
Could you please assign this issue to me?

**Comment by monizb** [comment]
Assigned!

**Comment by rahmat-st** [comment]
Hey @sprakash57 you still working on this? I'd like to help or take over if you don't have the time.

**Comment by kodelebah** [comment]
Hello @sprakash57, are you still working on this? I'd like to help or take over if you don't have the time.

**Comment by sprakash57** [comment]
Sure. go ahead.
